version: "3.7"

services:
  reverse-proxy:
    container_name: eshop-reverse-proxy
    image: eshop-reverse-proxy
    ports:
      - "80:9000"
  back-end:
    container_name: eshop-back-end
    image: eshop-back-end
    build:
      context: ./Back-End
      args:
        jar: rest-1.0-SNAPSHOT.jar
    ports:
      - "8081:8080"
    depends_on:
      - eshop-database
  eshop-database:
    restart: "always"
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "*E-Shop123*"
      MYSQL_DATABASE: e-shop
      MYSQL_USER: user
      MYSQL_PASSWORD: "*E-Shop123*"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5001:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uuser", "-p*E-Shop123*", "--port=5000"]
      timeout: 20s
      retries: 10