#!/usr/bin/env bash

# First we build the Back-End
cd Back-End
gradle clean build
sleep 3
gradle bootRun --args='--spring.config.additional-location=../environment/staging/application.yaml' &

function cleanupOnExit() {
  killall -9 node
  gradle -stop
  wait

  red=`tput setaf 1`
  green=`tput setaf 2`
  reset=`tput sgr0`
  printf "\n${red}----------------------------------------------------\n"
  printf "${red}------------- ${green}EXITED FROM THE PROGRAM!${red} -------------\n"
  printf "${red}----------------------------------------------------${reset}\n"

  kill -- -0
}

trap cleanupOnExit INT

# Then we create the bundle.js
#  injecting it in build folder of rest module in Back-End
cd ..
cd CMS
npm run-script magic &

while read -n1 -r v
do
  if [ $v = "r" ]; then
    npm run classic
  fi
  if [ $v = "s" ]; then
    gradle -stop
    sleep 3
    cd ../Back-End
    gradle build
    gradle bootRun --args='--spring.config.additional-location=../environment/staging/application.yaml'
    sleep 3
    cd ../CMS
  fi
  if [ $v = "l" ]; then
    cd ../Back-End
    sleep 3
    gradle build
    sleep 3
    cd ../CMS
  fi
done
