#!/usr/bin/env bash

# First we build the Back-End
cd Back-End
gradle bootRun &

function cleanupOnExit() {
  killall -9 node
  gradle -stop
  wait

  red=`tput setaf 1`
  green=`tput setaf 2`
  reset=`tput sgr0`
  printf "\n${red}----------------------------------------------------\n"
  printf "${red}------------- ${green}EXITED FROM THE PROGRAM!${red} -------------\n"
  printf "${red}----------------------------------------------------${reset}\n"
}

trap cleanupOnExit INT

# Then we create the bundle.js
#  injecting it in build folder of rest module in Back-End
cd ..
cd CMS
npm run-script magic