spring:
  datasource:
    url: "jdbc:mysql://eshop-database:3306/e-shop"
    username: "root"
    password: "*E-Shop123*"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: create

    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080