spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:5000/e-shop?useSSL=false&serverTimezone=Europe/Zurich&autoReconnect=true&maxReconnects=40&allowPublicKeyRetrieval=true"
    username: "root"
    password: "*E-Shop123*"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081