spring:
  datasource:
    url: "jdbc:mysql://localhost:8889/e-shop"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081